# Simply read a single PixC netcdf

In [2]:
from pixcdust.readers.netcdf import NcSimpleReader
import glob

In [3]:
swot_nc_files = glob.glob('/tmp/pixc/**/*.nc',recursive=True)

In [4]:
path = swot_nc_files[0]

# You can specify conditions on variables to filter data
conditions= {"sig0":{'operator': "gt", 'threshold': 20},  # sig0 > 20
             "classification":{'operator': "ge", 'threshold': 3},  # classification >= 3
            }

ncsimple = NcSimpleReader(path, variables=['height', 'sig0', 'classification'], conditions=conditions)

In [5]:
ncsimple.read()
ncsimple.data

<xarray.Dataset> Size: 4MB
Dimensions:         (points: 106257)
Coordinates:
  * points          (points) geometry 850kB POINT (0.7496681431523484 43.7694...
    latitude        (points) float64 850kB 43.77 43.77 43.77 ... 43.26 43.27
    longitude       (points) float64 850kB 0.7497 0.7515 0.7535 ... 1.195 1.242
Data variables:
    height          (points) float32 425kB 237.8 237.3 236.8 ... 266.7 361.0
    sig0            (points) float32 425kB 48.02 124.2 1.622e+03 ... 21.24 40.77
    classification  (points) float32 425kB 3.0 7.0 4.0 7.0 ... 3.0 3.0 4.0 6.0
Indexes:
    points   GeometryIndex (crs=EPSG:4326)
Attributes:
    description:                 cloud of geolocated interferogram pixels
    interferogram_size_azimuth:  3245
    interferogram_size_range:    4857
    looks_to_efflooks:           1.5340684990936673
    num_azimuth_looks:           7.0
    azimuth_offset:              3

In [6]:
# show some information
str_time_start, dt_time_start, cycle_number, pass_number, tile_number, swath_size = (
    ncsimple.extract_info_from_nc_attrs(path)
)
print(dt_time_start, cycle_number, pass_number, tile_number)

2023-04-06 09:46:18 482 16 78

## use data with xarray

In [7]:
ncsimple.to_xarray() # same thing as ncsimple.data

<xarray.Dataset> Size: 4MB
Dimensions:         (points: 106257)
Coordinates:
  * points          (points) geometry 850kB POINT (0.7496681431523484 43.7694...
    latitude        (points) float64 850kB 43.77 43.77 43.77 ... 43.26 43.27
    longitude       (points) float64 850kB 0.7497 0.7515 0.7535 ... 1.195 1.242
Data variables:
    height          (points) float32 425kB 237.8 237.3 236.8 ... 266.7 361.0
    sig0            (points) float32 425kB 48.02 124.2 1.622e+03 ... 21.24 40.77
    classification  (points) float32 425kB 3.0 7.0 4.0 7.0 ... 3.0 3.0 4.0 6.0
Indexes:
    points   GeometryIndex (crs=EPSG:4326)
Attributes:
    description:                 cloud of geolocated interferogram pixels
    interferogram_size_azimuth:  3245
    interferogram_size_range:    4857
    looks_to_efflooks:           1.5340684990936673
    num_azimuth_looks:           7.0
    azimuth_offset:              3

## use data with pandas.dataframe

In [8]:
ncsimple.to_dataframe()

,height,sig0,classification,latitude,longitude
points,,,,,
POINT (0.74967 43.76945),237.849167,48.017120,3.0,43.769451,0.749668
POINT (0.75154 43.7698),237.287689,124.176331,7.0,43.769799,0.751545
POINT (0.7535 43.77016),236.775909,1621.530151,4.0,43.770162,0.753499
POINT (0.74622 43.76881),235.316193,1215.073853,7.0,43.768810,0.746219
POINT (0.74975 43.76947),234.851242,118.526390,7.0,43.769466,0.749751
...,...,...,...,...,...
POINT (1.08348 43.23709),304.885925,146.800751,3.0,43.237093,1.083477
POINT (1.08716 43.23777),306.263824,38.899006,3.0,43.237769,1.087164
POINT (1.15169 43.24958),281.268951,41.687149,3.0,43.249585,1.151694
POINT (1.19549 43.25758),266.691193,21.244059,4.0,43.257580,1.195485
POINT (1.24242 43.26613),361.047852,40.774483,6.0,43.266126,1.242419

## use data with geopandas.geodataframe

In [9]:
gdf = ncsimple.to_geodataframe()
gdf

,points,height,sig0,classification,latitude,longitude
0,POINT (0.74967 43.76945),237.849167,48.017120,3.0,43.769451,0.749668
1,POINT (0.75154 43.7698),237.287689,124.176331,7.0,43.769799,0.751545
2,POINT (0.7535 43.77016),236.775909,1621.530151,4.0,43.770162,0.753499
3,POINT (0.74622 43.76881),235.316193,1215.073853,7.0,43.768810,0.746219
4,POINT (0.74975 43.76947),234.851242,118.526390,7.0,43.769466,0.749751
...,...,...,...,...,...,...
106252,POINT (1.08348 43.23709),304.885925,146.800751,3.0,43.237093,1.083477
106253,POINT (1.08716 43.23777),306.263824,38.899006,3.0,43.237769,1.087164
106254,POINT (1.15169 43.24958),281.268951,41.687149,3.0,43.249585,1.151694
106255,POINT (1.19549 43.25758),266.691193,21.244059,4.0,43.257580,1.195485
106256,POINT (1.24242 43.26613),361.047852,40.774483,6.0,43.266126,1.242419